### ISSUE TITLE
Support SFW domains

### ISSUE THREAD

**Issue by macklinu** [sprngr/hubot-domain-me#1]
Hello,

I really like this hubot script and would like to integrate it into my company's hubot instance. However, we try to keep it pretty SFW and wanted to modify [`words.json`](https://github.com/sprngr/hubot-domain-me/blob/master/src/dict/words.json) to be more work appropriate.

My thought was to contribute a SFW words list. A quick idea on the implementation would be something like:

```coffee
# rename words.json to nsfw-words.json

# come up with a bunch of sfw words in sfw-words.json

# in src/domain-me.coffee
words = if process.env.HUBOT_DOMAIN_ME_IS_SFW # defaults to false; NSFW by default
        then require('./dict/sfw-words.json')
        else require('./dict/nfsw-words.json')
```

Would you be open to a PR with this change? Thanks!

**Comment by sprngr** [comment]
I hear you man, if you want to make a PR I'd be open for it, otherwise I'll gladly get a sfw flag setup soon.

**Comment by macklinu** [comment]
Awesome, thanks! I'll take a shot at it over the next day or so and make a PR. I think the hardest part will be the SFW words list.

**Comment by sprngr** [comment]
Yeah, I figured I could take a crack at it later today. Definitely open to suggestions for the SFW words.

**Comment by macklinu** [comment]
If you'd like to make the changes, that's cool with me too.

First thing I thought of for random nouns was some sort of Heroku name generator. After Googling, [this gist](https://gist.github.com/afriggeri/1266756#file-haiku-L13) provides some nouns. These nouns aren't the funniest though, but perhaps a start?

**Comment by sprngr** [comment]
Good idea. I had also received a suggestion to replace a random letter in the nsfw.dict with # @ ! $ like in the sunday comics. Any thoughts on that?

**Comment by sprngr** [comment]
Also came across http://listofrandomwords.com/, could be a good source of words to pick from.

**Comment by macklinu** [comment]
In my case, I still worry about people getting offended by something like `b$$bies` or `cl#wnp@n!s`. I think that would be a funny feature for both a NSFW and SFW words list though. Turning normal words into "inappropriate" words like `baseball -> b***ball` is funny to me, but that could be a whole other feature.

I'll look for other random word generators/lists too and share them here. Also, if there's an initial random SFW word list, even if it's not the most expansive, I could get it integrated into my company's hubot and get feedback/suggestions from coworkers for how to improve the words list.

**Comment by sprngr** [comment]
Totally understand, I should be able to get something rolling later this afternoon.

**Comment by macklinu** [comment]
Awesome, thanks for the help/being open to the idea!

**Comment by sprngr** [comment]
Thanks for bringing it up! I had contemplated if it was a tad risqué, but our hubot users get a kick out of it.

**Comment by sprngr** [comment]
@macklinu I have a pull request open, #2, if you want to check it out and see if this works to suit your needs.

**Comment by sprngr** [comment]
1.1.0 is live on NPM, closing out this issue. Thanks!
